### ISSUE TITLE
ME3Logger - Bad Export Index values are off by  (-1)

### ISSUE THREAD

**Issue by Mgamerz** [Erik-JS/ME3-ASI#2]
I've been dealing with some fun bad export index values, and learned from kinko that the index listed in heff's logger is off by -1. I have no idea if this is fixable or in the game, but the values thrown into ME3Log.txt will be off by 1. You need to add 1 to the bad export index to get the real value, which you can then search for in a hex editor.

**Comment by Erik-JS** [comment]
Export index? Are you talking about exports from PCC's? Like logger says error on export index 2, and you have to actually search for value 3? If it's like this, then it's actually an engine "feature".
